version: 1.0.{build}
image: Visual Studio 2019

platform: x64

build:
  project: my_project.py

test_script:
  - python --version  # Überprüft, ob Python korrekt installiert ist
  - python my_project.py  # Führt dein Skript aus
