version: 1.0.{build}
image: Visual Studio 2019
platform: x64

install:
  - ps: |
      $pythonInstaller = "https://www.python.org/ftp/python/3.8.10/python-3.8.10-amd64.exe"
      $installerPath = "C:\projects\python_installer.exe"
      Invoke-WebRequest -Uri $pythonInstaller -OutFile $installerPath
      Start-Process -FilePath $installerPath -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1" -Wait
  - pip install telepot
  - pip install requests


build_script:
  # 1) Starte den Bot in einem neuen PowerShell-Prozess und gib das Process-Objekt zurück
  - ps: |
      $proc = Start-Process -FilePath python -ArgumentList 'bot.py' -WindowStyle Hidden -PassThru
      Write-Host "Bot gestartet mit PID $($proc.Id)"
  # 2) Warte 15 Sekunden, damit log.txt gefüllt wird
  - ps: Start-Sleep -Seconds 15
  # 3) Beende den Bot-Prozess
  - ps: |
      if ($proc -and -not $proc.HasExited) {
        Stop-Process -Id $proc.Id -Force
        Write-Host "Bot-Prozess $($proc.Id) gestoppt."
      } else {
        Write-Host "Bot-Prozess bereits beendet."
      }


test_script:
  - echo "Keine Tests vorhanden. Alles okay."
artifacts:
  - path: log.txt  # Die log.txt wird hier gespeichert
    name: Logs       # Du kannst den Namen ändern, wie du möchtest
