version: 1.0.{build}
image: Visual Studio 2019
platform: x64

install:
  - ps: |
      $pythonInstaller = "https://www.python.org/ftp/python/3.8.10/python-3.8.10-amd64.exe"
      $installerPath = "C:\projects\python_installer.exe"
      Invoke-WebRequest -Uri $pythonInstaller -OutFile $installerPath
      Start-Process -FilePath $installerPath -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1" -Wait
  - pip install telepot
  - pip install requests


build_script:
  # 1) Bot im Hintergrund starten
  - ps: Start-Process -FilePath python -ArgumentList "bot.py" -WindowStyle Hidden -PassThru | Out-Variable botProcess
  # 2) ein paar Sekunden warten, damit log.txt gefüllt wird
  - timeout /t 15
  # 3) Prozess beenden
  - ps: Stop-Process -Id $botProcess.Id -Force

test_script:
  - echo "Keine Tests vorhanden. Alles okay."
artifacts:
  - path: log.txt  # Die log.txt wird hier gespeichert
    name: Logs       # Du kannst den Namen ändern, wie du möchtest
