version: 1.0.{build}
image: Visual Studio 2019

platform: x64

environment:
  python: "3.8"  # Gebe die gewünschte Python-Version an

install:
  - ps: Install-Product Python $env:python # Dieses Kommando sollte in AppVeyor bereits funktionieren

build:
  project: my_project.py  # Dein Python-Skript oder Projekt

test_script:
  - python -m unittest discover  # Beispiel für Unit-Tests
