version: 1.0.{build}
image: Visual Studio 2019

platform: x64

install:
  - ps: |
      $pythonInstaller = "https://www.python.org/ftp/python/3.8.10/python-3.8.10-amd64.exe"
      $installerPath = "C:\projects\python_installer.exe"
      Invoke-WebRequest -Uri $pythonInstaller -OutFile $installerPath
      Start-Process -FilePath $installerPath -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1" -Wait

# Hier läuft Dein "Build" – in unserem Fall einfach Python-Befehle
build_script:
  - python --version
  - python my_project.py

# Wenn Du noch einen separaten Test‑Step brauchst, kannst Du den so anfügen:
test_script:
  - python -m unittest discover
